<?php
// vim: set ts=2 sw=2 sts=2 et:

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software info@qtmsoft.com
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-2016 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Form_Cc
 */
?>
<?php if ($this->isVisible()): ?>

  <ul id="payment_form_xpayments">
    <li>
      <div id="xpayment-iframe-block">

        <iframe id="xp-iframe" class="xp-iframe" src="" name="xp-iframe"></iframe>
        <div id="paymentstep-ajax-loader"></div>

      </div>
    </li>
  </ul>

  <script type="text/javascript">
  //<![CDATA[
      document.fire('xpc:iframeBlockLoaded');
  //]]>
  </script>

<?php endif; ?>
