<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software info@qtmsoft.com
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-2016 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Control
 */
?>
<?php if ($this->getRequiremenetsErrors()) { ?>

    <h4><?php echo $this->__('Failed to meet environment requirements'); ?></h4>
    <ul>
        <?php foreach ($this->getRequiremenetsErrors() as $err) { ?>
            <li class="error"><?php echo $this->__($err); ?></li>
        <?php } ?>
    </ul>
    <br/>
<?php } ?>

<div class="xpayment-info">
    <div class="content-header">
        <table cellspacing="0">
            <tbody>
            <tr>
                <td>
                    <h3>
                        <?php echo $this->__('X-Payments connector'); ?>
                    </h3>
                </td>
            </tr>
            </tbody>
        </table>
    </div>

    <?php if ($this->getConfigurationErrors()) { ?>
        <p><strong>
                <h4 class="sub-heading">
                    <?php echo $this->__('X-Payments not configured yet. Please, check x-payment'); ?>
                    <a href="<?php echo $this->getUrl('adminhtml/system_config/edit/section/xpaymentsconnector/'); ?>"
                       target="_blank">
                        <strong>
                            <?php echo $this->__('settings') ?>
                        </strong>
                    </a>
                </h4>
            </strong>
        </p>

        <div class="payment-description">
            <div class="payment-logo">
                <img src="<?php echo Mage::getBaseUrl('js') . 'xpayment/images/xpayment-logo.png'; ?>"
                     alt="xpayments connector"/>
            </div>
            <div class="description-block">
                <p>

                    <?php
                    $xpDescr = "Give your customers – and yourself – peace of mind with this payment processing module "
                        . "that guarantees compliance with PCI security mandates, significantly reduces the risk of "
                        . "data breaches and ensures you won’t be hit with a fine of up to $500,000 for non-compliance. "
                        . "Safely and conveniently store customers credit card information to use for new orders, reorders "
                        . "or recurring payments.";
                    echo $this->__($xpDescr); ?>
                </p>
            </div>
        </div>

        <h4>
            <?php echo $this->__('Connect to X-Payments in 3 easy steps:'); ?>
        </h4>
        <div class="payment-step">
            <div class="step">
                <span class="step-number">1</span>
                <p><?php echo $this->__('Open your'); ?>
                    <a href="http://www.x-payments.com/trial-demo.html?utm_source=mage_shop&utm_medium=link&utm_campaign=mage_shop_link"
                       target="_blank">
                        <?php echo $this->__('X-Payments'); ?>
                    </a>
                    <?php echo $this->__('back-end (if you do not have it)'); ?>
                </p>
                <button onclick="window.open('http://www.x-payments.com/trial-demo.html?utm_source=mage_shop&utm_medium=link&utm_campaign=mage_shop_link');">
                    <span>
                        <span>
                            <span>
                                <?php echo $this->__('Start free Trial'); ?>
                            </span>
                        </span>
                    </span>
                </button>
            </div>
            <img src="<?php echo Mage::getBaseUrl('js') . 'xpayment/images/atep-arrow.png' ?>" class=" step-arrow">
            <div class="step">
                <span class="step-number">2</span>

                <p>
                    <?php echo $this->__('Configure payment methods at'); ?>
                    <strong>
                        <?php echo $this->__('X-Payments'); ?>
                    </strong>
                </p>
                <a href="http://help.x-cart.com/index.php?title=X-Payments:User_manual#Online_Stores" target="_blank">
                    <?php echo $this->__('Read how to do that'); ?>
                </a>
            </div>
            <img src="<?php echo Mage::getBaseUrl('js') . 'xpayment/images/atep-arrow.png' ?>" class=" step-arrow">
            <div class="step">
                <span class="step-number">3</span>
                <p>
                    <?php echo $this->__('Connect'); ?>
                    <strong>
                        <?php echo $this->__('X-Payments'); ?>
                    </strong>
                    <?php echo $this->__('with'); ?>
                    <strong>
                        <?php echo $this->__('Magento'); ?>
                    </strong>
                </p>
                <a href="https://www.youtube.com/embed/2VRR0JW23qc" target="_blank">See how to do that</a>
            </div>
        </div>
    <?php } ?>
</div>
<?php if ($this->getConfigurationErrors()): ?>
    <hr/>
<?php endif; ?>
<br/>

<h4><?php echo $this->__('Test module'); ?></h4>

<p><?php echo $this->__("To test the module settings and connection with X-Payments click the button below. If the module is configured properly, a 'Test transaction completed successfully' message will be displayed at the top of the page."); ?></p>

<form action="<?php echo $this->getUrl('xpaymentsconnector/control/test'); ?>" method="post" name="testmodule_form">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <?php echo $this->getChildHtml('testButton'); ?>
</form>

<br/>
<br/>

<h4><?php echo $this->__('Import payment methods'); ?></h4>

<p><?php echo $this->__('To be able to use X-Payments payment methods you need to import them from X-Payments first.'); ?></p>

<?php if ($this->isMethodsRequested()) { ?>

    <?php echo $this->__('The list of payment configurations imported from X-Payments'); ?>:<br/>

    <div class="grid">
        <table cellpadding="5" cellspacing="1">
            <tr class="headings">
                <th><?php echo $this->__('Payment method'); ?></th>
                <th><?php echo $this->__('Payment method ID'); ?></th>
                <th><?php echo $this->__('Auth'); ?></th>
            </tr>

            <?php foreach ($this->getPaymentMethods() as $pm) { ?>

                <tr>
                    <td><?php echo $pm['name']; ?></td>
                    <td><?php echo $pm['confid']; ?></td>
                    <td><?php if ($pm['is_auth']) { ?><?php echo $this->__('Yes'); ?><?php } else { ?><?php echo $this->__('No'); ?><?php } ?></td>
                </tr>

            <?php } ?>

        </table>
    </div>

    <form action="<?php echo $this->getUrl('xpaymentsconnector/control/clear'); ?>" method="post" name="clear_form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <?php echo $this->getChildHtml('clearButton'); ?>
    </form>

    <?php if ($this->isMethodsAlreadyImported()) { ?>
        <br/>
        <br/>
        <p><?php echo $this->__('Warning! Importing payment configurations from X-Payments will disable the X-Payments connector payment method!'); ?></p>
    <?php } ?>

<?php } ?>

<form action="<?php echo $this->getUrl('xpaymentsconnector/control/request'); ?>" method="post" name="request_form">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <?php echo $this->getChildHtml('requestButton'); ?>
</form>

<br/>
<br/>
<h4>
    <?php echo $this->__('Need help in settings of x-payments?'); ?>
    <a href="http://www.x-payments.com/contact-us.html?utm_source=mage_shop&utm_medium=link&utm_campaign=mage_shop_link" target="_blank">
        <?php echo $this->__('Contact us!'); ?>
    </a>
</h4>