<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software info@qtmsoft.com
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-2016 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Customer_Usercards
 */
?>
<?php $_items = $this->getItems(); ?>
<?php $cardUsageOptions = $this->getCardsUsageOptions();?>
<div class="page-title">
    <h1><?php echo $this->__('Edit payment cards list (X-Payments)') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('pager'); ?>
<form  id="credit-card-list-form" method="post" action="<?php echo Mage::getUrl("xpaymentsconnector/customer/usercards");?>">
    <?php if(count($_items)): ?>
        <table class="data-table" id="my-credit-cards-table">
            <col width="1" />
            <col width="1" />
            <col />
            <col width="1" />
            <col width="1" />
            <thead>
            <tr>
                <th><a id="select-all-cards" href="#" onclick="addRelatedCard(event)">Select all</a>
                    /
                    <a id="unselect-all-cards" href="#" onclick="removeRelatedCard(event)">Unselect all</a></th>
                <th><?php echo $this->__('Card id #') ?></th>
                <th><?php echo $this->__('Card number') ?></th>
                <th><?php echo $this->__('Usage card type'); ?></th>
                <th><?php echo $this->__('Card type'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($_items as $_item): ?>
                <tr>
                    <td><input type="checkbox" class="checkbox related-checkbox"
                               value="<?php echo $_item->getXpCardId();?>" name="card[]"></td>
                    <td><?php echo $_item->getXpCardId();?></td>
                    <td>
                        <?php
                            $xpCardDataStr = Mage::helper('xpaymentsconnector')->prepareCardDataString($_item->getData());
                            echo $xpCardDataStr;
                        ?>
                    </td>
                    <td><?php echo $cardUsageOptions[$_item->getUsageType()];?></td>
                    <td>
                        <span class="x-payment-card-logo-list <?php echo strtolower($_item->getCardType()) ?>"
                              title="<?php echo $_item->getCardType();?>">
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <input type="hidden" name="action" value="remove">

        <script type="text/javascript">decorateTable('my-credit-cards-table')</script>
    <?php else: ?>
        <p><?php echo $this->__('You have no saved credit cards yet.'); ?></p>
    <?php endif; ?>
    <?php echo $this->getChildHtml('pager'); ?>
    <div class="buttons-set">
        <p class="back-link">
            <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
                <small>&laquo; </small><?php echo $this->__('Back') ?>
            </a>
        </p>
        <?php  if(count($_items)):  ?>
            <button class="button" title="Save" type="submit"><span><span>Remove</span></span></button>
        <?php endif; ?>
        <button onclick="window.location='<?php echo $this->getAddCardUrl();?>'"
                class="button" title="Add new card" type="button"><span><span>Add new card</span></span></button>
    </div>
</form>

<script type="text/javascript">
    //<![CDATA[

    function addRelatedCard(event){
        Event.stop(event)
        var checkboxes = $$('.related-checkbox');
        var values = [];
        for(var i=0;i<checkboxes.length;i++){
            checkboxes[i].checked = true;
        }
    }
    function removeRelatedCard(event){
        Event.stop(event)
        var checkboxes = $$('.related-checkbox');
        var values = [];
        for(var i=0;i<checkboxes.length;i++){
            checkboxes[i].checked = false;
        }
    }
    //]]>
</script>

