<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software info@qtmsoft.com
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-2016 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Form_Savedcards
 */
?>
<?php $_code = $this->getMethodCode() ?>
<?php $userAdminhtmlCreditCardsList = $this->getAdminhtmlUserCreditCardsList(); ?>
<?php
    $admSession = Mage::getSingleton('adminhtml/session');
    $cardSelected = $admSession->getData('xp_payment_card');
?>

<?php if( $userAdminhtmlCreditCardsList && ($userAdminhtmlCreditCardsList->getSize()>0)):?>
    <ul id="payment_form_<?php echo $_code ?>" class="adminhtml-payment-form" style="display:none;">
            <?php foreach($userAdminhtmlCreditCardsList as $key => $creditCard):?>
                <?php
                    $xpCardDataStr = Mage::helper('xpaymentsconnector')->prepareCardDataString($creditCard->getData());
                    $checked = ($creditCard->getXpCardId() == $cardSelected) ? "checked" : "";
                ?>

                <li>
                    <span class="input-box">
                        <input disabled="" type="radio" <?php echo $checked;?>
                               title="<?php echo "'".$creditCard->getCardType()."'"; ?> - credit card"
                               class="input-radio  x-payment-card validate-one-required-by-name"
                               id="<?php echo $_code."_".$creditCard->getXpCardId(); ?>"
                               name="payment[xp_payment_card]"
                               value="<?php echo $creditCard->getXpCardId();?>" />
                        <label for="<?php echo $_code."_".$creditCard->getData("xp_card_id") ?>">
                            <?php echo $this->__('Use card - %s', $xpCardDataStr); ?>
                        </label>

                        <span class="x-payment-card-logo <?php echo strtolower($creditCard->getCardType()) ?>"
                              title="<?php echo $creditCard->getCardType();?>"></span>
                    </span>

                </li>
            <?php endforeach;?>
    </ul>
<?php endif;?>

