<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software info@qtmsoft.com
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-2016 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @see Cdev_XPaymentsConnector_Block_Beforesuccess
 */
?>

<html>
<head>
    <link href="<?php echo $this->getJsUrl("xpayment/settings.css"); ?>" type="text/css" rel="stylesheet">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js">
        <script>
    </script>
</head>

<body>
<div id="wait-message">
    <strong>
        <?php echo Mage::helper('xpaymentsconnector')->__('Please wait, your order is being created ...'); ?>
    </strong>
</div>

<div class="b-loader-wrap">
    <div id="ajax-loader">
    </div>
</div>

<?php $formKey = Mage::getSingleton('core/session')->getFormKey();?>

<script type="text/javascript">
    jQuery(document).ready(function () {
        var dataObj = {};
/*        if (jQuery("#checkout-agreements", window.parent.document).length) {
            jQuery("#checkout-agreements input", window.parent.document).each(function (obj, item) {
                dataObj[item.name] = item.value;
            });
        } else {
            <?php if ($this->getAgreements()): ?>
                <?php foreach($this->getAgreements() as $_a):?>
                    dataObj['agreement[<?php echo $_a->getId()?>]'] = 1;
                <?php endforeach;?>
            <?php endif; ?>
        }
*/
//		 window.location = "<?php echo $this->getCheckoutSuccessUrl();?>";

        dataObj["payment[method]"] = "<?php echo $this->getXpaymentsCode();?>";
        dataObj["form_key"] = "<?php echo $formKey;?>";

        jQuery.ajax({
            url: "<?php echo Mage::getUrl('checkout/onepage/saveorder'); ?>",
            type: "post",
            data: jQuery.param(dataObj),
            success: function (data) {
                var response = jQuery.parseJSON(data);
                if (response.success == true) {
                    window.location = "<?php echo $this->getCheckoutSuccessUrl();?>";
                } else if (response.success == false) {
                    if (response['error_messages']) {
                        alert(response['error_messages']);
                    }
                    if (response['redirect'] != undefined) {
                        window.parent.location = response['redirect'];
                    } else {
                        window.parent.location = "<?php echo Mage::getUrl();?>";
                    }
                }
            },
            error: function () {
            }
        });
    });
</script>
</body>

</html>
