<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software info@qtmsoft.com
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-2016 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Cancel
 */
?>
<html>
<head>
   <meta http-equiv="refresh" content="0; URL=<?php echo $this->getContinueShoppingUrl(); ?>" />
    <link href="<?php echo $this->getJsUrl("xpayment/settings.css"); ?>" type="text/css" rel="stylesheet">
</head>
<body>

<div class="b-loader-wrap">
    <div id="ajax-loader">
    </div>
</div>
<div id="wait-message">
    <div class="page-head">
        <h3><?php echo Mage::helper('xpaymentsconnector')->__('The payment has been canceled') ?></h3>
    </div>
    <p><?php echo Mage::helper('xpaymentsconnector')->__('Please')?>&nbsp;
        <a href="<?php echo $this->getContinueShoppingUrl();?>">
            <?php echo Mage::helper('xpaymentsconnector')->__('continue shopping.');?>
        </a>
    </p>
</div>
</body>
</html>
