<?php
// vim: set ts=4 sw=4 sts=4 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software info@qtmsoft.com
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-2016 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Redirect
 */
?>

<?php if ($this->checkToken()): ?>

    <form id="xpc-iframe-redirect" action="<?php echo $this->getFormAction(); ?>" method="post">
        <?php foreach ($this->getFormData() as $name => $value): ?>
            <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>" />
        <?php endforeach; ?>
    </form>

    <script type="text/javascript">
    //<![CDATA[
        var paymentform = document.getElementById('xpc-iframe-redirect');
        if (paymentform) {
            window.onload = function() {
                paymentform.submit();
            }
        }
    //]]>
    </script>

<?php else: ?>

    <script type="text/javascript">
    //<![CDATA[
        var msg = {
            message: 'paymentFormSubmitError',
            params: {
                height: 0,
                error: 'Oops... Something wrong has happened. Please restart checkout.',
                type: 1
            }
        };

        window.parent.postMessage(JSON.stringify(msg), '*');
    //]]>
    </script>

<?php endif; ?>
