<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software info@qtmsoft.com
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-2016 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Redirect
 */
?>

<div class="b-loader-wrap">
    <div id="ajax-loader">
    </div>
</div>

<p id="wait-message">
    <strong>
        <?php echo Mage::helper('xpaymentsconnector')->__('You are being redirected to the payment form. Please wait a few seconds.'); ?>
    </strong>
</p>
<form name="xpaymentsconnector_checkout" id="xpaymentsconnector_checkout" action="<?php echo $this->getFormAction();?>" method="POST">
<?php if (is_array($this->getFormData())): ?>
    <?php foreach ($this->getFormData() as $name => $value): ?>
        <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>" />
    <?php endforeach; ?>
<?php endif; ?>
</form>

<script type="text/javascript">
//<![CDATA[
    var paymentform = document.getElementById('xpaymentsconnector_checkout');
	if (paymentform) {
	    window.onload = function() {
			paymentform.submit();
		}
	}
//]]>
</script>
